version: '3.9'
services:
  web:
    volumes:
        - "smilecook-volume:/home/flask"
    build: .
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    
  db:
    volumes:
      - "db-volume:/var/lib/data"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "smilecook"
      POSTGRES_PASSWORD: "lyric_lice_clippers"
    
volumes:
    db-volume:
      name: db-volume
      external: true

    smilecook-volume:
      external: true
      name: smilecook-volume