"""empty message

Revision ID: 0ea4588fa345
Revises: b5738da074cf
Create Date: 2022-08-12 21:46:17.741356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea4588fa345'
down_revision = 'b5738da074cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cover_image', sa.String(length=100), nullable=True))
    op.drop_column('user', 'cover_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cover_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'cover_image')
    # ### end Alembic commands ###
