"""empty message

Revision ID: 9a3d26e8d74e
Revises: 6c85ab97d39a
Create Date: 2022-08-10 22:36:57.951949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3d26e8d74e'
down_revision = '6c85ab97d39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_cover', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_cover')
    # ### end Alembic commands ###
