    openapi: 3.0.0
    info:
      title:  Smilecook apllication REST API
      description: RESTAPI created for a recipe application created with the Python Flask Framework and using some extentensions to provide more functioniality on top off Flask like
      version: 0.1.9
    servers:
      # - url: https://127.0.0.1:5000
      #   description: Optional server description, e.g. Main (production) server
      - url: http://127.0.0.1:5000
        description: Development server
    paths:
      /recipes:
        get:
          summary: Returns a list of users.
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
      /recipes/{recipe_id}:
        get:
          summary: Returns a list of users.
          parameters:
            - in : path
              name: recipe_id
              schema:
                type: integer
              required: true
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /recipes/{recipe_id}/publish:
        put:
          summary: Publish recipe while providing the recipe id.
          parameters:
            - in : path
              name: recipe_id
              schema:
                type: integer
              required: true
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /recipes/{recipe_id}/cover:
        put:
          summary: TODO
          parameters:
            - in : path
              name: recipe_id
              schema:
                type: integer
              required: true
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /users:
        get:
          summary: TODO
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
      /token:
        post:
          summary: TODO
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
      /me:
        get:
          summary: TODO
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
      /refresh:
        post:
          summary: TODO
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /revoke:
        post:
          summary: TODO
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /users/{username}:
        get:
          summary: TODO
          parameters:
            - in : path
              name: username
              schema:
                type: string
              required: true
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /users/{username}/recipes:
        get:
          summary: TODO
          parameters:
            - in : path
              name: username
              schema:
                type: string
              required: true
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /users/activate/token:
        get:
          summary: TODO
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

      /users/avatar:
        put:
          summary: TODO
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string

