"""empty message

Revision ID: 04dd1eee97d8
Revises: 7a199b19a896
Create Date: 2022-07-12 21:58:35.937092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dd1eee97d8'
down_revision = '7a199b19a896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('num_of_servings', sa.Integer(), nullable=True))
    op.drop_column('recipe', 'num_of_serving')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('num_of_serving', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'num_of_servings')
    # ### end Alembic commands ###
